AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'pkg/**/*'

plugins:
  - rubocop-rake
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
